# General parameters
dataset: imagenet-small
expid: imagenet_run
mode: scala
seed: 4
numClasses: 2

# CKM Parameters
layers: 1
patch_sizes: [5]
bandwidth: [1.0]
pool: [126]
poolStride: [126]
filters: [200]
whiten: True
whitenerValue: 0.01
whitenerOffset: 0.1
featureDir: /user/vaishaal/
labelDir: /home/eecs/vaishaal/ckm/mldata/imagenet-small
modelDir: /home/eecs/vaishaal/models

# Solver Params
solve: True
reg: 0
yarn: True
solverWeight: 0
blockSize: 1024
numBlocks: 20
numIters: 1

