# General parameters
dataset: imagenet-small
expid: imagenet_run
mode: scala
seed: 1
numClasses: 2

# CKM Parameters
layers: 1
patch_sizes: [5]
bandwidth: [1.0]
pool: [16]
poolStride: [16]
filters: [4]
whiten: True
whitenerValue: 0.01
whitenerOffset: 0.1
featureDir: /scratch/vaishaal/ckm/mldata/
labelDir: /scratch/vaishaal/ckm/mldata/imagenet-small/

# Solver Params
solve: True
reg: 0
yarn: False
solverWeight: 0
blockSize: 1024
numBlocks: 20
numIters: 1

