# General parameters
dataset: imagenet
expid: imagenet_run
mode: scala
seed: 9
numClasses: 10

# CKM Parameters
layers: 1
patch_sizes: [5]
bandwidth: [1.0]
pool: [16]
poolStride: [16]
filters: [256]
whiten: True
whitenerValue: 0.01
whitenerOffset: 0.1

# Solver Params
solve: True
saveFeatures: False
solver: BlockWeightedLeastSquares 
kernelGamma: 5e-8
reg: 0
solverWeight: 0
blockSize: 4096
numBlocks: 20
numIters: 1

